baseurl: "/blog"
url: "https://divayprakash.github.io"

theme_settings:
  title: 633k
  avatar: divayprakash
  description: "A geek's worldview!"

  header_text: >
    <p>Hello! I'm Divay Prakash and welcome to my blog <a href="https://divayprakash.github.io/blog">633k</a>.</p>
    <p>
      This is just an outlet for a stream of random and sometimes not-so-random thoughts so please bear with me.
      And if you find it fun, then do stick around for more! You can check out my latest posts below.
    </p>
  header_text_feature_image:
  footer_text: >
    <p>Made with 💙 by <a href="https://divayprakash.github.io/">Divay Prakash</a></p>

  rss: true
  website: https://divayprakash.github.io/
  email_address: divayprakash3@gmail.com
  facebook:
  github: divayprakash
  google_plus: u/0/+DivayPrakash
  instagram:
  linkedin: https://www.linkedin.com/in/divayprakash/
  twitter: divayprakash3
  
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true

  str_follow_on: "Follow me on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Previous"
  str_continue_reading: "Continue reading"

  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  post_navigation: true

paginate: 5
paginate_path: "blog/page:num"

markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-avatar
