baseurl: "/blog"
url: "https://divayprakash.github.io"

theme_settings:
  title: 633k
  avatar: divayprakash
  description: "A geek's eclectic oeuvre"

  header_text_feature_image:

  rss: true
  website: https://divayprakash.github.io/
  email_address: divayprakash3@gmail.com
  facebook: 1333414176673744
  github: divayprakash
  google_plus: u/0/+DivayPrakash
  linkedin: https://www.linkedin.com/in/divayprakash/
  twitter: divayprakash3
  
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true

  str_follow_on: "Follow me on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Previous"
  str_continue_reading: "Continue reading"

  google_fonts: "Source+Sans+Pro:400,400i|Signika:400,700"

  post_navigation: true

paginate: 5
paginate_path: "blog/page:num"

markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-avatar
